# Generated by Django 4.1.3 on 2022-12-17 11:39

import django.core.validators
from django.db import migrations, models
import servicecatalogue.core.modelsvalidators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), servicecatalogue.core.modelsvalidators.validate_is_letters_only]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='last_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), servicecatalogue.core.modelsvalidators.validate_is_letters_only]),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), servicecatalogue.core.modelsvalidators.validate_is_letters_only]),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='job',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='last_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), servicecatalogue.core.modelsvalidators.validate_is_letters_only]),
        ),
    ]
