# Generated by Django 4.1.3 on 2022-12-17 09:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, help_text='YYYY-MM-DD')),
                ('timeslot', models.IntegerField(choices=[(0, '10:00'), (1, '11:00'), (2, '12:00'), (3, '13:00'), (4, '14:00'), (5, '15:00'), (6, '16:00'), (7, '17:00'), (8, '18:00')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.providerprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.service')),
            ],
            options={
                'unique_together': {('provider', 'date', 'timeslot')},
            },
        ),
    ]
